# Generated by Django 3.2.7 on 2021-09-21 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
